### ISSUE TITLE
unterminated regular expression

### ISSUE THREAD

**Issue by morrowd** [PwCUK-CTO/SANSCTISummit2021-xStart#1]
YARA does not like your comments and is generating an error **xstart.yar(2): error: unterminated regular expression** when executing. I believe this is the culprit 
**"/ *
Copyright 2021 PwC UK"** note the space after your comment. Not a big deal but thought I would mention it.

**Comment by BitsOfBinary** [comment]
Thanks @morrowd, I've fixed this multi-line comment in e1b22a9a587594b4bc5689501f7363e9066d4f94.
